Add Helper Functions
Sourav-Patteri/UpwardorPortalVue pull request #2
Opened 2024-03-12 04:11 UTC by Sourav-Patteri

Added a few helper functions, a function to handle form submission and a calculate quote function.

2024-03-12 08:12 UTC, ksaswin requested changes

2024-03-12 08:12 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +  <form @submit.prevent="handleFormSubmit">
Use single quotes wherever possible.

2024-03-12 08:12 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +const selectedDoorHeight = ref<string>("");
Use single quotes.
Does removing `null` affect the select in any way?

2024-03-12 08:12 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +  const suffixes: Record<string, string> = {
Could you define this as an Enum and move the same to `src/models/orders.ts`.
Or you could even extend the `KeyValuesSelects` interface to optionally hold this value as well.

2024-03-12 08:12 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +  const suffixes: Record<string, string> = {
Could you move this to `src/models/orders.ts`?

2024-03-12 08:12 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +  const panelsTable: Record<string, Record<string, number>> = {
Could you move this to `src/models/orders.ts`, please?

2024-03-12 08:12 UTC, ksaswin commented on src/store/store.ts
The `store.ts` file can be removed if empty.

2024-03-12 08:12 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +const handleFormSubmit = () => {
Could you declare the function in the following sytanx? (Just to keep it consistent in the project)
```ts
function handleFormSubmit(): void {
  // ...
}
```

2024-03-12 08:12 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +const calculateQuote = () => {
Could you declare the function in the following sytanx? (Just to keep it consistent in the project)
```ts
function calculateQuote(): void {
  // ...
}
```

2024-03-12 08:12 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +  calculateQuote();
If the handleFormSubmit does not have any other logic, `calculateQuote()` could be called directly from the form submit event

2024-03-13 01:03 UTC, closed without merging

2024-03-13 01:03 UTC, Sourav-Patteri commented
Reviewed and resolved requested changes