Add helper functions
Sourav-Patteri/UpwardorPortalVue pull request #4
Opened 2024-03-13 02:32 UTC by Sourav-Patteri

Updated code and resolved conversation. Added logic for other part numbers.

2024-03-13 05:17 UTC, ksaswin requested changes

2024-03-13 05:17 UTC, ksaswin commented on src/components/Logo.vue
> +    <div class="logo-container">
Single quotes wherever possible, please.

2024-03-13 05:17 UTC, ksaswin commented on src/components/Logo.vue
> +      <img src="@/assets/UpwardorLogo.png" alt="Logo">
Same here (single quotes).

2024-03-13 05:17 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +const generatePanelPartNumber = (
Declare such functions using the following syntax:
```ts
function generatePanelPartNumber(): string => {
  // ...
}
```

2024-03-13 05:17 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +  const panelPartNumber = generatePanelPartNumber(isPanelsOnlyOrder.value, selectedDoorHeight.value, selectedDoorWidth.value, doors.value, selectedStampPattern.value, selectedPanelColor.value);
The `ref` variables can be accessed within the `generatePanelPartNumber` function as well!

I would suggest simplifying the function definition for `generatePanelPartNumber` and update it here as:
```ts
const panelPartNumber = generatePanelPartNumber();
```

Or better, create a getter using `computed`:
```ts
// The panelPartNumber getter
const panelPartNumber = computed((): string => {
  // ...
});
```
The value can be accessed using `panelPartNumber.value`

2024-03-13 05:17 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +  const bulkPanelPrefix = bulkPanelsValue === true ? 'PN60' : 'PN65';
Could be simplified:

```ts
const bulkPanelPrefix = bulkPanelsValue ? 'PN60' : 'PN65';
```

2024-03-13 05:17 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +    if (panelCount > 0) {
Style guide:
Leave an empty line before statements (like `if`, `return`, ...)

2024-03-13 05:17 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +
Could you remove the empty line here, please?

2024-03-14 00:27 UTC, Sourav-Patteri commented on src/components/QuoteGenerator.vue
> +const generatePanelPartNumber = (
You mean- 
``function generatePanelPartNumber(): string {}``

2024-03-14 05:03 UTC, ksaswin requested changes

2024-03-14 05:03 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +    const panelPartNumber = computed((): string => {
Could you move this computed value outside `handleFormSubmit`, please?

```ts
const panelPartNumber = computed((): string => {
  //...
  return ‘value’;
});

function handleFormSubmit(): void {
  //...
console.log(`Your quote: Panel Part Numbers - ${panelPartNumber.value}….`); 
}
```

2024-03-14 05:03 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +  let frameTypeNum = chosenFrameSize.value === 'short' ? 0 : 1;
Prefer `const` if you don’t plan to change the value.

2024-03-14 05:08 UTC, ksaswin requested changes

2024-03-14 05:08 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +
Could you remove the trailing spaces here?

2024-03-14 11:52 UTC, ksaswin requested changes

2024-03-14 11:52 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +  let frameTypeNum = chosenFrameSize.value === 'short' ? 0 : 1;
Please remove the trailing spaces at the end of line 234.

2024-03-14 11:52 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +  const glazingKitPart = `GK15-1${frameTypeNum}${selectedPanelColor.value}-00`
Missing semi-colon.

2024-03-14 11:52 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +};
You don’t need a semi-colon here :)

2024-03-14 11:52 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +
Remove trailing spaces in lines 202 and 205 as well.

2024-03-14 17:10 UTC, ksaswin approved these changes

2024-03-14 17:10 UTC, ksaswin commented on src/components/QuoteGenerator.vue
> +      // Define the bulk panel prefix
Fix the indentation in lines 203 -> 224 (use two blankspaces and not tabs to keep the consistensy across all editors out there).
And feel free to merge the PR.

2024-03-14 17:17 UTC, merged